#Transfer & duplications tokens: 
#D|rank|named_branch|g_id
;#T(|rank|t|named_branch|g_id)>(|rank|t|named_branch|gp_id)>.. or 
#>(|rank|t|named_branch|-1), where g_id=-1 is the root of G.
D|0|Cow|8
D|1|Human|9
D|0|Human|7
D|0|Cow|8
D|1|Human|9
D|0|Human|7
D|0|Cow|8
D|0|Human|9
D|0|Human|7
D|0|Cow|8
D|1|Human|9
D|0|Human|7
D|0|Cow|8
D|1|Human|9
D|0|Human|7
D|0|Cow|8
D|1|Human|9
D|0|Human|7
D|0|Cow|8
D|1|Human|9
D|1|Human|7
D|0|Cow|8
D|1|Human|9
D|0|Human|7
D|0|Cow|8
D|0|Human|9
D|0|Human|7
D|0|Cow|8
D|1|Human|9
D|0|Human|7
